# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  # build stage
  build:  
    working_directory: ~/repo           # Specify the working directory
    docker:                             # Add the infrastructure
      - image: circleci/node:14
    steps:                              # Tasks will be done in build stage
      - checkout                        # Checkout the code to the working directory
      - run: npm ci                     # Install dependencies
      - run: CI=false npm run build     # Start build process
      - persist_to_workspace:           # Persist the specified path from ~/repo into the workspace, to be used by another job in the workflow 
          root: ~/repo
          paths: ['.']
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:               # Attach the workflow's workspace to the current container
          at: .
      - run: npm run test               # Run tests
  save:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:                # store the artifacts after the project is built, to be used by deployment later
          path: ./build
          destination: build/
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - run:                            # Automatic deploy to Firebase
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

# Invoke jobs via workflows
workflows:
  build_test_and_deploy:    # This is the name of the workflow
    jobs:
    - build
    - test:
        requires:
          - build
    - save:
        requires:
          - test
    - deploy:
        requires:
          - test
        filters:          # Deploy from master branch only
          branches:
            only:
              - master
