# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  # build stage
  build:  
    working_directory: ~/repo           # Specify the working directory
    docker:                             # Add the infrastructure
      - image: circleci/node:14
    steps:                              # Tasks will be done in build stage
      - checkout                        # Checkout the code to the working directory
      - run: npm ci                     # Install dependencies
      - run: CI=false npm run build     # Start build process
      - persist_to_workspace:           # Persist the specified path from ~/repo into the workspace, to be used by another job in the workflow 
          root: ~/repo
          paths: ['.']
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:               # Attach the workflow's workspace to the current container
          at: .
      - run: npm run test               # Run tests

# Invoke jobs via workflows
workflows:
  build_test_and_deploy:    # This is the name of the workflow
    jobs:
    - build
    - test:
        requires:
          - build
